language: node_js
node_js: stable 
install:
    - npm install 
script:
    - hexo clean
    - hexo g 
after_script:
  - cd ./public
  - git init
  - git config user.name "chencc"
  - git config user.email "932322877@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Update"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master
branches:
    only:
        - dev 
env:
    global:
        - GH_REF: git@github.com:cc-ch/cc-ch.github.io.git 