language: node_js
node_js: stable 
install:
    - npm install 
script:
    - hexo clean
    - hexo g 
after_script:
    - hexo deploy
branches:
    only:
        - dev 
env:
    global:
        - GH_REF: git@github.com:cc-ch/cc-ch.github.io.git 